@host=http://localhost:5179
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MzBhNjAxNi1kZDRlLTQxMTEtYTY4YS0yMmU2ZWJlMjFjNzIiLCJnaXZlbl9uYW1lIjoiQW1pa28iLCJmYW1pbHlfbmFtZSI6IkRhcmsiLCJqdGkiOiJhZTk1NGM4OC0xMTM3LTRlNjAtOGE0Ny05ZjU4ZWJjNTg4MzkiLCJleHAiOjE3MjUxMTMxNzUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.LPBQw2CzY160kSPskNdYRr4Q1yXTqrsGEFoU_DvKGXk
@hostId=asdf

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}