@host=https://localhost:7193

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNzc3YjE5Zi03NzlkLTQ0NGEtOTAyYi0yN2JhYzk4N2Y4ZmUiLCJnaXZlbl9uYW1lIjoiVmlqYXkiLCJmYW1pbHlfbmFtZSI6Ikt1bWFyIiwianRpIjoiN2U0MzNjNjAtNTY0Ni00YjY5LWFiYjAtMmFmZTM1NjQ1ZDdiIiwiZXhwIjoxNzI0NDk3NTM4LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.KQ9L4HJoqdbAP4olGhDuEYDMNwpmfYkAAJv82eoIqnY